// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBungiLc2qiwmoww9mFhXIih_IIfMdRONg',
    appId: '1:451938534000:web:a60b828238477fff64eab5',
    messagingSenderId: '451938534000',
    projectId: 'footbollmatch-e1a65',
    authDomain: 'footbollmatch-e1a65.firebaseapp.com',
    storageBucket: 'footbollmatch-e1a65.appspot.com',
    measurementId: 'G-DLQSPBRY73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4OIcHZSEr01dyZJDLhcvUN3sQD3hzB0',
    appId: '1:451938534000:android:b3f7f402d04cbf8f64eab5',
    messagingSenderId: '451938534000',
    projectId: 'footbollmatch-e1a65',
    storageBucket: 'footbollmatch-e1a65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSD6r9kQf3k6n23aZEL2UTfqittFSntl8',
    appId: '1:451938534000:ios:7b51176d60c1f64064eab5',
    messagingSenderId: '451938534000',
    projectId: 'footbollmatch-e1a65',
    storageBucket: 'footbollmatch-e1a65.appspot.com',
    iosBundleId: 'com.example.battingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSD6r9kQf3k6n23aZEL2UTfqittFSntl8',
    appId: '1:451938534000:ios:7b51176d60c1f64064eab5',
    messagingSenderId: '451938534000',
    projectId: 'footbollmatch-e1a65',
    storageBucket: 'footbollmatch-e1a65.appspot.com',
    iosBundleId: 'com.example.battingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBungiLc2qiwmoww9mFhXIih_IIfMdRONg',
    appId: '1:451938534000:web:7c2f6d39f7b1844464eab5',
    messagingSenderId: '451938534000',
    projectId: 'footbollmatch-e1a65',
    authDomain: 'footbollmatch-e1a65.firebaseapp.com',
    storageBucket: 'footbollmatch-e1a65.appspot.com',
    measurementId: 'G-GZ082CT9HM',
  );

}